smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -426,12 +426,8 @@ jobs:
               BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
               API_URL="http://${BACKEND_IP}:3030"
               echo "api url: ${API_URL}"
-              if curl "${API_URL}/api/status" | grep "ok"
-              then
-                exit 0
-              else
-                exit 1
-              fi
+              echo "Mock fail smoke test Bakend"
+              exit 1
       - revert-migrations 
       - destroy-environment
       - slack-notification
